export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_LECTURERS = 'FETCH_LECTURERS';
export const FETCH_TIMETABLE = 'FETCH_TIMETABLE';
export const FETCH_TIMETABLE_ERROR = 'FETCH_TIMETABLE_ERROR';
export const UPDATE_TIMETABLE = 'UPDATE_TIMETABLE';
export const SET_CURRENT_TIMETABLE = 'SET_CURRENT_TIMETABLE';
